openapi: 3.0.2
info:
  description: >-
    This is the HOTH (Hyperscaler Orchestration and Tracking Helper) API, a private internal-facing API that is intended
    to be purely consumed by the ServiceNow component of ATAT
  version: "0.1"
  title: ATAT HOTH API - ServiceNow Integration
  contact:
    email: replaceme@ccpo.mil
tags:
  - name: provisioning
    description: >-
      Operations related to provisioning jobs
  - name: document
    description: >-
      Operations related to document generation requests
paths:
  /generate-document:
    post:
      tags:
        - document
      description: Generates a document
      operationId: generateDocument
      responses:
        "200":
          description: Successful operation
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseTooLargeError"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GenerateDocumentRequest"
  /provisioning-jobs:
    get:
      tags:
        - provisioning
      description: Consumes and returns up to ten of the most recently completed Provisioning Jobs from the Provisioning Queue
      operationId: consumesProvisioningJobs
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProvisioningRequest"
    post:
      tags:
        - provisioning
      description: Starts a new Provisioning Job
      operationId: startProvisioningJob
      responses:
        "201":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProvisioningRequest"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProvisioningRequest"
    options:
      tags:
        - cors
      description: CORS headers
      responses:
        "200":
          $ref: "#/components/responses/CorsHeaders"
components:
  responses:
    CorsHeaders:
      description: Default response for CORS method
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string
        Access-Control-Allow-Methods:
          schema:
            type: string
        Access-Control-Allow-Headers:
          schema:
            type: string
      content: {}
  schemas:
    Error:
      type: object
      additionalProperties: false
      description: Generic error model
      required:
        - message
      properties:
        message:
          type: string
    ValidationError:
      allOf:
        - $ref: "#/components/schemas/Error"
        - type: object
          additionalProperties: false
          required:
            - error_map
          properties:
            error_map:
              type: object
              description: Maps form input IDs to validation error messages so that clients can display in-line errors
    ResponseTooLargeError:
      description: If the response exceeds 6MB response limit, this is returned as an error response
      allOf:
        - $ref: "#/components/schemas/Error"
      type: object
      required:
        - responseSize
        - maxAllowed
      properties:
        responseSize:
          type: number
          description: Represents the size of the PDF to send back to the user
        maxAllowed:
          type: number
          description: Represents the maximum allowed size to return
    ProvisioningRequest:
      description: Represents a generic request for provisioning cloud resources via ATAT
      type: object
      additionalProperties: false
      required:
        - job_id
        - user_id
        - portfolio_id
        - operation_type
        - target_csp
        - payload
      properties:
        job_id:
          description: ID of the Provisioning Job assigned by DISA StoreFront Service Now
          type: string
        user_id:
          description: ID of the Mission Owner in DISA StoreFront Service Now
          type: string
        portfolio_id:
          description: ID of the CSP Portfolio assigned by DISA StoreFront Service Now (not to be confused with the ID generated by the CSP)
          type: string
        operation_type:
          $ref: "#/components/schemas/OperationType"
        target_csp:
          $ref: "#/components/schemas/TargetCloudServiceProvider"
        payload:
          oneOf:
            - $ref: "#/components/schemas/NewPortfolioPayload"
            - $ref: "#/components/schemas/FundingSourcePayload"
            - $ref: "#/components/schemas/OperatorPayload"
        response:
          description: Response from the CSP which will be set after a request has been processed
          $ref: "#/components/schemas/CspResponse"
          readOnly: true
    OperationType:
      description: Distinguishes type of operation that a user is performing
      type: string
      enum:
        - ADD_PORTFOLIO
        - ADD_OPERATORS
        - ADD_FUNDING_SOURCE
    TargetCloudServiceProvider:
      description: Distinguishes the cloud where the provisioning operation will occur
      properties:
        name:
          $ref: "#/components/schemas/TargetCloudServiceProviderName"
        uri:
          type: string
          description: Base URI of Target CSP's ATAT implementation
        network:
          $ref: "#/components/schemas/TargetNetwork"
    TargetCloudServiceProviderName:
      description: List of available CSPs by name
      type: string
      enum:
        - CSP_A
        - CSP_B
        - CSP_C
        - CSP_D
    TargetNetwork:
      description: Distinguishes the network where the provisioning operation will occur
      type: string
      enum:
        - NETWORK_1
        - NETWORK_2
        - NETWORK_3
    ProvisioningPayload:
      description: Abstract base model describing the payloads for provisioning operations
    NewPortfolioPayload:
      description: Payload for creation of a new CSP Portfolio
      allOf:
        - $ref: "#/components/schemas/ProvisioningPayload"
      required:
        - name
        - funding_sources
        - operators
      properties:
        name:
          type: string
          description: Name of the Portfolio being created
        funding_sources:
          type: array
          items:
            $ref: "#/components/schemas/FundingSource"
        operators:
          type: array
          description: Array of operator email addresses
          items:
            type: string
            example: "user@mail.mil"
        csp_id:
          type: string
          readOnly: true
    FundingSourcePayload:
      description: Payload for the addition of a Funding Source to an existing CSP Portfolio
      allOf:
        - $ref: "#/components/schemas/ProvisioningPayload"
      required:
        - funding_sources
      properties:
        funding_sources:
          type: array
          items:
            $ref: "#/components/schemas/FundingSource"
    OperatorPayload:
      description: Payload for the addition of an Operator to an existing CSP Portfolio
      allOf:
        - $ref: "#/components/schemas/ProvisioningPayload"
      required:
        - operators
      properties:
        operators:
          type: array
          description: Array of operator email addresses
          items:
            type: string
            example: "user@mail.mil"
    FundingSource:
      type: object
      description: >-
        A Task Order and CLIN used to pay for provisioned resources and services
      required:
        - task_order_number
        - clin
        - pop_start_date
        - pop_end_date
      properties:
        task_order_number:
          type: string
          example: "1234567891234"
        clin:
          type: string
          example: "0001"
        pop_start_date:
          type: string
          format: date
          example: "2021-07-01"
        pop_end_date:
          type: string
          format: date
          example: "2022-07-01"
    CspInvocation:
      required:
        - method
        - endpoint
        - payload
      properties:
        method:
          type: string
          enum:
            - GET
            - POST
            - PUT
            - DELETE
        headers:
          type: object
          additionalProperties:
            type: string
        endpoint:
          type: string
          format: uri
        payload:
          type: object
    CspResponse:
      required:
        - code
        - content
      properties:
        code:
          type: integer
        content:
          type: object
          additionalProperties: true
    GenerateDocumentRequest:
      oneOf:
        - $ref: "#/components/schemas/DescriptionOfWork"
    DescriptionOfWork:
      description: "Schema used to generate DescriptionOfWork document"
      type: object
      properties:
        to_title:
          type: string
          maxLength: 60
        scope:
          type: string
          maxLength: 300
        scope_surge:
          type: integer
          maximum: 50
        current_environment: # DOW section 3
          $ref: "#/components/schemas/CurrentEnvironment"
        performance_requirements: # DOW section 4
          $ref: "#/components/schemas/PerformanceRequirements"
    CurrentEnvironment:
      description: "Part of DOW, encapsulates all data for 3. Background/Current Environment section."
      properties:
        current_environment_exists:
          type: boolean
        environment_instances:
          type: array
          items:
            $ref: "#/components/schemas/EnvironmentInstance"
          maxItems: 4000
        additional_info:
          type: string
          maxLength: 1000
    EnvironmentInstance:
      description: "Part of DOW, represents a single Environment Instance"
      properties:
        instance_name:
          type: string
          maxLength: 100
        classification_level:
          $ref: "#/components/schemas/ClassificationLevel"
        instance_location:
          type: string
          enum:
            - CSP
            - Hybrid
            - Not in the cloud / On-premise
        csp_region:
          $ref: "#/components/schemas/TargetCloudServiceProviderName" #On the SNOW side, this is CSP_REGION a choice field with no options, so using TargetCSPName instead
        performance_tier: # This is also an empty choice on the SNOW side, set as empty String until we get details
          type: string
        pricing_model:
          type: string
          enum:
            - On-demand
            - Pay-as-you-go
            - Reserved
        pricing_model_expiration:
          type: string
          format: date
          example: "2022-07-01"
        operating_system_licensing:
          type: string
          maxLength: 1000
        number_of_vCPUs:
          type: integer
          maximum: 40
        storage_type:
          type: string # Empty choice on SNOW side, set as empty String until we get details
        storage_amount:
          type: integer
          maximum: 40
        storage_unit:
          $ref: "#/components/schemas/StorageUnit"
        memory_amount:
          type: integer
          maximum: 40
        memory_unit:
          $ref: "#/components/schemas/StorageUnit"
        data_egress_monthly_amount:
          type: integer
          maximum: 40
        data_egress_monthly_unit:
          $ref: "#/components/schemas/StorageUnit"
    ClassificationLevel:
      description: "Part of DOW, Classification Level table fields"
      properties:
        classification:
          type: string
          enum:
            - Unclassified
            - Top Secret
            - Secret
        impact_level:
          type: string
          nullable: true
          enum:
            - IL2
            - IL4
            - IL5
            - IL6
            - null
    StorageUnit:
      description: "Part of DOW, used in EnvironmentInstance schema"
      type: string
      enum:
        - GB
        - TB
    PerformanceRequirements:
      description: "Part of DOW, encapsulates all data for 4. Performance Requirements"
      properties:
        required_services:
          type: array
          items:
            $ref: "#/components/schemas/RequiredService"
          maxItems: 4000
    RequiredService:
      description: "Part of DOW, represents a single required service"
      properties:
        applicable_classification_levels:
          type: array
          items:
            $ref: "#/components/schemas/ClassificationLevel"
          maxItems: 4000 # This is the limit in SNOW, but it doesn't actually make sense to have a 4000 limit because there aren't 4000 classification levels
        usage_description:
          type: string
          maxLength: 1000
        need_for_entire_TO_duration:
          type: boolean
        applicable_periods:
          type: array
          items:
            $ref: "#/components/schemas/Period"
        service_offerings: # represents the "Select Service Offerings" field
          type: array
          items:
            $ref: "#/components/schemas/ServiceOffering"
        other_service_offering:
          type: string
          maxLength: 100
    Period:
      description: "Part of DOW, represents Period Table fields"
      properties:
        period_type:
          type: string
          enum:
            - Base
            - Option
        period_unit_count:
          type: integer
        period_unit:
          type: string
          enum:
            - Day(s)
            - Week(s)
            - Month(s)
            - Year(s)
        option_order:
          type: integer
    ServiceOffering:
      description: "Part of DOW, represents a single Service Offering (Service Offering table)"
      properties:
        service_offering_group:
          type: string
          enum:
            - Advanced Technology and Algorithmic Techniques (Machine Learning)
            - Advisory and Assistance
            - Applications
            - Compute
            - Database with Storage
            - Developer Tools and Services
            - Edge Computing and Tactical Edge (TE)
            - General IaaS, PaaS, and SaaS
            - Internet of Things (IoT)
            - Networking
            - Security
            - Training
        name:
          type: string
          maxLength: 100
