openapi: 3.0.2
info:
  description: >-
    This is the HOTH (Hyperscaler Orchestration and Tracking Helper) API, a private internal-facing API that is intended
    to be purely consumed by the ServiceNow component of ATAT
  version: "0.1"
  title: ATAT HOTH API - ServiceNow Integration
  contact:
    email: replaceme@ccpo.mil
tags:
  - name: provisioning
    description: >-
      Operations related to provisioning jobs
  - name: document
    description: >-
      Operations related to document generation requests
paths:
  /generate-document:
    post:
      tags:
        - document
      description: Generates a document
      operationId: generateDocument
      responses:
        "200":
          description: Successful operation
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseTooLargeError"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GenerateDocumentRequest"
  /provisioning-jobs:
    get:
      tags:
        - provisioning
      description: Consumes and returns up to ten of the most recently completed Provisioning Jobs from the Provisioning Queue
      operationId: consumesProvisioningJobs
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProvisioningRequest"
    post:
      tags:
        - provisioning
      description: Starts a new Provisioning Job
      operationId: startProvisioningJob
      responses:
        "201":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProvisioningRequest"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProvisioningRequest"
    options:
      tags:
        - cors
      description: CORS headers
      responses:
        "200":
          $ref: "#/components/responses/CorsHeaders"
components:
  responses:
    CorsHeaders:
      description: Default response for CORS method
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string
        Access-Control-Allow-Methods:
          schema:
            type: string
        Access-Control-Allow-Headers:
          schema:
            type: string
      content: {}
  schemas:
    Error:
      type: object
      additionalProperties: false
      description: Generic error model
      required:
        - message
      properties:
        message:
          type: string
    ValidationError:
      allOf:
        - $ref: "#/components/schemas/Error"
        - type: object
          additionalProperties: false
          required:
            - error_map
          properties:
            error_map:
              type: object
              description: Maps form input IDs to validation error messages so that clients can display in-line errors
    ResponseTooLargeError:
      description: If the response exceeds 6MB response limit, this is returned as an error response
      allOf:
        - $ref: "#/components/schemas/Error"
      type: object
      required:
        - responseSize
        - maxAllowed
      properties:
        responseSize:
          type: number
          description: Represents the size of the PDF to send back to the user
        maxAllowed:
          type: number
          description: Represents the maximum allowed size to return
    ProvisioningRequest:
      description: Represents a generic request for provisioning cloud resources via ATAT
      type: object
      additionalProperties: false
      required:
        - job_id
        - user_id
        - portfolio_id
        - operation_type
        - target_csp
        - payload
      properties:
        job_id:
          description: ID of the Provisioning Job assigned by DISA StoreFront Service Now
          type: string
        user_id:
          description: ID of the Mission Owner in DISA StoreFront Service Now
          type: string
        portfolio_id:
          description: ID of the CSP Portfolio assigned by DISA StoreFront Service Now (not to be confused with the ID generated by the CSP)
          type: string
        operation_type:
          $ref: "#/components/schemas/OperationType"
        target_csp:
          $ref: "#/components/schemas/TargetCloudServiceProvider"
        payload:
          oneOf:
            - $ref: "#/components/schemas/NewPortfolioPayload"
            - $ref: "#/components/schemas/FundingSourcePayload"
            - $ref: "#/components/schemas/OperatorPayload"
        response:
          description: Response from the CSP which will be set after a request has been processed
          $ref: "#/components/schemas/CspResponse"
          readOnly: true
    OperationType:
      description: Distinguishes type of operation that a user is performing
      type: string
      enum:
        - ADD_PORTFOLIO
        - ADD_OPERATORS
        - ADD_FUNDING_SOURCE
    TargetCloudServiceProvider:
      description: Distinguishes the cloud where the provisioning operation will occur
      properties:
        name:
          $ref: "#/components/schemas/TargetCloudServiceProviderName"
        uri:
          type: string
          description: Base URI of Target CSP's ATAT implementation
        network:
          $ref: "#/components/schemas/TargetNetwork"
    TargetCloudServiceProviderName:
      description: List of available CSPs by name
      type: string
      enum:
        - CSP_A
        - CSP_B
        - CSP_C
        - CSP_D
    TargetNetwork:
      description: Distinguishes the network where the provisioning operation will occur
      type: string
      enum:
        - NETWORK_1
        - NETWORK_2
        - NETWORK_3
    ProvisioningPayload:
      description: Abstract base model describing the payloads for provisioning operations
    NewPortfolioPayload:
      description: Payload for creation of a new CSP Portfolio
      allOf:
        - $ref: "#/components/schemas/ProvisioningPayload"
      required:
        - name
        - funding_sources
        - operators
      properties:
        name:
          type: string
          description: Name of the Portfolio being created
        funding_sources:
          type: array
          items:
            $ref: "#/components/schemas/FundingSource"
        operators:
          type: array
          description: Array of operator email addresses
          items:
            type: string
            example: "user@mail.mil"
        csp_id:
          type: string
          readOnly: true
    FundingSourcePayload:
      description: Payload for the addition of a Funding Source to an existing CSP Portfolio
      allOf:
        - $ref: "#/components/schemas/ProvisioningPayload"
      required:
        - funding_sources
      properties:
        funding_sources:
          type: array
          items:
            $ref: "#/components/schemas/FundingSource"
    OperatorPayload:
      description: Payload for the addition of an Operator to an existing CSP Portfolio
      allOf:
        - $ref: "#/components/schemas/ProvisioningPayload"
      required:
        - operators
      properties:
        operators:
          type: array
          description: Array of operator email addresses
          items:
            type: string
            example: "user@mail.mil"
    FundingSource:
      type: object
      description: >-
        A Task Order and CLIN used to pay for provisioned resources and services
      required:
        - task_order_number
        - clin
        - pop_start_date
        - pop_end_date
      properties:
        task_order_number:
          type: string
          example: "1234567891234"
        clin:
          type: string
          example: "0001"
        pop_start_date:
          type: string
          format: date
          example: "2021-07-01"
        pop_end_date:
          type: string
          format: date
          example: "2022-07-01"
    CspInvocation:
      required:
        - method
        - endpoint
        - payload
      properties:
        method:
          type: string
          enum:
            - GET
            - POST
            - PUT
            - DELETE
        headers:
          type: object
          additionalProperties:
            type: string
        endpoint:
          type: string
          format: uri
        payload:
          type: object
    CspResponse:
      required:
        - code
        - content
      properties:
        code:
          type: integer
        content:
          type: object
          additionalProperties: true
    GenerateDocumentRequest:
      oneOf:
        - $ref: "#/components/schemas/DescriptionOfWork"
    DescriptionOfWork:
      description: "TODO: AT-7341, define DescriptionOfWork schema"
      type: object
