openapi: 3.0.2
info:
  description: >-
    This is the HOTH (Hyperscaler Orchestration and Tracking Helper) API, a private internal-facing API that is intended
    to be purely consumed by the ServiceNow component of ATAT
  version: "0.1"
  title: ATAT HOTH API - ServiceNow Integration
  contact:
    email: replaceme@ccpo.mil
tags:
  - name: provisioning
    description: >-
      Operations related to provisioning jobs
  - name: document
    description: >-
      Operations related to document generation requests
paths:
  /generate-document:
    post:
      tags:
        - document
      description: Generates a document
      operationId: generateDocument
      responses:
        "200":
          description: Successful operation
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseTooLargeError"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GenerateDocumentRequest"
  /provisioning-jobs:
    get:
      tags:
        - provisioning
      description: Consumes and returns up to ten of the most recently completed Provisioning Jobs from the Provisioning Queue
      operationId: consumesProvisioningJobs
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProvisioningRequest"
    post:
      tags:
        - provisioning
      description: Starts a new Provisioning Job
      operationId: startProvisioningJob
      responses:
        "201":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProvisioningRequest"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProvisioningRequest"
    options:
      tags:
        - cors
      description: CORS headers
      responses:
        "200":
          $ref: "#/components/responses/CorsHeaders"
components:
  responses:
    CorsHeaders:
      description: Default response for CORS method
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string
        Access-Control-Allow-Methods:
          schema:
            type: string
        Access-Control-Allow-Headers:
          schema:
            type: string
      content: {}
  schemas:
    Error:
      type: object
      additionalProperties: false
      description: Generic error model
      required:
        - message
      properties:
        message:
          type: string
    ValidationError:
      allOf:
        - $ref: "#/components/schemas/Error"
        - type: object
          additionalProperties: false
          required:
            - error_map
          properties:
            error_map:
              type: object
              description: Maps form input IDs to validation error messages so that clients can display in-line errors
    ResponseTooLargeError:
      description: If the response exceeds 6MB response limit, this is returned as an error response
      allOf:
        - $ref: "#/components/schemas/Error"
      type: object
      required:
        - responseSize
        - maxAllowed
      properties:
        responseSize:
          type: number
          description: Represents the size of the PDF to send back to the user
        maxAllowed:
          type: number
          description: Represents the maximum allowed size to return
    ProvisioningRequest:
      description: Represents a generic request for provisioning cloud resources via ATAT
      type: object
      additionalProperties: false
      required:
        - job_id
        - user_id
        - portfolio_id
        - operation_type
        - target_csp
        - payload
      properties:
        job_id:
          description: ID of the Provisioning Job assigned by DISA StoreFront Service Now
          type: string
        user_id:
          description: ID of the Mission Owner in DISA StoreFront Service Now
          type: string
        portfolio_id:
          description: ID of the CSP Portfolio assigned by DISA StoreFront Service Now (not to be confused with the ID generated by the CSP)
          type: string
        operation_type:
          $ref: "#/components/schemas/OperationType"
        target_csp:
          $ref: "#/components/schemas/TargetCloudServiceProvider"
        payload:
          oneOf:
            - $ref: "#/components/schemas/NewPortfolioPayload"
            - $ref: "#/components/schemas/FundingSourcePayload"
            - $ref: "#/components/schemas/OperatorPayload"
        response:
          description: Response from the CSP which will be set after a request has been processed
          $ref: "#/components/schemas/CspResponse"
          readOnly: true
    OperationType:
      description: Distinguishes type of operation that a user is performing
      type: string
      enum:
        - ADD_PORTFOLIO
        - ADD_OPERATORS
        - ADD_FUNDING_SOURCE
    TargetCloudServiceProvider:
      description: Distinguishes the cloud where the provisioning operation will occur
      properties:
        name:
          $ref: "#/components/schemas/TargetCloudServiceProviderName"
        uri:
          type: string
          description: Base URI of Target CSP's ATAT implementation
        network:
          $ref: "#/components/schemas/TargetNetwork"
    TargetCloudServiceProviderName:
      description: List of available CSPs by name
      type: string
      enum:
        - CSP_A
        - CSP_B
        - CSP_C
        - CSP_D
    TargetNetwork:
      description: Distinguishes the network where the provisioning operation will occur
      type: string
      enum:
        - NETWORK_1
        - NETWORK_2
        - NETWORK_3
    ProvisioningPayload:
      description: Abstract base model describing the payloads for provisioning operations
    NewPortfolioPayload:
      description: Payload for creation of a new CSP Portfolio
      allOf:
        - $ref: "#/components/schemas/ProvisioningPayload"
      required:
        - name
        - funding_sources
        - operators
      properties:
        name:
          type: string
          description: Name of the Portfolio being created
        funding_sources:
          type: array
          items:
            $ref: "#/components/schemas/FundingSource"
        operators:
          type: array
          description: Array of operator email addresses
          items:
            type: string
            example: "user@mail.mil"
        csp_id:
          type: string
          readOnly: true
    FundingSourcePayload:
      description: Payload for the addition of a Funding Source to an existing CSP Portfolio
      allOf:
        - $ref: "#/components/schemas/ProvisioningPayload"
      required:
        - funding_sources
      properties:
        funding_sources:
          type: array
          items:
            $ref: "#/components/schemas/FundingSource"
    OperatorPayload:
      description: Payload for the addition of an Operator to an existing CSP Portfolio
      allOf:
        - $ref: "#/components/schemas/ProvisioningPayload"
      required:
        - operators
      properties:
        operators:
          type: array
          description: Array of operator email addresses
          items:
            type: string
            example: "user@mail.mil"
    FundingSource:
      type: object
      description: >-
        A Task Order and CLIN used to pay for provisioned resources and services
      required:
        - task_order_number
        - clin
        - pop_start_date
        - pop_end_date
      properties:
        task_order_number:
          type: string
          example: "1234567891234"
        clin:
          type: string
          example: "0001"
        pop_start_date:
          type: string
          format: date
          example: "2021-07-01"
        pop_end_date:
          type: string
          format: date
          example: "2022-07-01"
    CspInvocation:
      required:
        - method
        - endpoint
        - payload
      properties:
        method:
          type: string
          enum:
            - GET
            - POST
            - PUT
            - DELETE
        headers:
          type: object
          additionalProperties:
            type: string
        endpoint:
          type: string
          format: uri
        payload:
          type: object
    CspResponse:
      required:
        - code
        - content
      properties:
        code:
          type: integer
        content:
          type: object
          additionalProperties: true
    GenerateDocumentRequest:
      oneOf:
        - $ref: "#/components/schemas/DescriptionOfWork"
    DescriptionOfWork:
      description: "Schema used to generate DescriptionOfWork document"
      type: object
      properties:
        to_title:
          type: string
          maxLength: 60
        scope:
          type: string
          maxLength: 300
        scope_surge:
          type: integer
          maximum: 50
        current_environment: # DOW section 3
          $ref: "#/components/schemas/CurrentEnvironment"
        performance_requirements: # DOW section 4 (and its subtasks)
          $ref: "#/components/schemas/PerformanceRequirements"
        # DOW section 5 TBD
        # DOW section 6 TBD
        period_of_performance: # DOW section 7
          $ref: "#/components/schemas/PeriodOfPerformance"
        # DOW section 8 TBD
        gfe_overview: # DOW section 9
          $ref: "#/components/schemas/GFEOverview"
        contract_considerations: # DOW section 10 (and its subtasks)
          $ref: "#/components/schemas/ContractConsiderations"
        section_508_accessibility_standards: # DOW section 11
          $ref: "#/components/schemas/SensitiveInformation"
    CurrentEnvironment:
      description: "Part of DOW, encapsulates all data for 3. Background/Current Environment section."
      properties:
        current_environment_exists:
          type: boolean
        environment_instances:
          type: array
          items:
            $ref: "#/components/schemas/EnvironmentInstance"
        additional_info:
          type: string
    EnvironmentInstance:
      description: "Part of DOW, represents a single Environment Instance"
      properties:
        instance_name:
          type: string
        classification_level:
          $ref: "#/components/schemas/ClassificationLevel"
        instance_location:
          type: string
          enum:
            - CSP
            - Hybrid
            - Not in the cloud / On-premise
        csp_region:
          $ref: "#/components/schemas/TargetCloudServiceProviderName" #On the SNOW side, this is CSP_REGION a choice field with no options, so using TargetCSPName instead
        performance_tier: # This is also an empty choice on the SNOW side, set as empty String until we get details
          type: string
        pricing_model:
          type: string
          enum:
            - On-demand
            - Pay-as-you-go
            - Reserved
        pricing_model_expiration:
          type: string
          format: date
          example: "2022-07-01"
        operating_system_licensing:
          type: string
        number_of_vCPUs:
          type: integer
        storage_type:
          type: string # Empty choice on SNOW side, set as empty String until we get details
        storage_amount:
          type: integer
        storage_unit:
          $ref: "#/components/schemas/StorageUnit"
        memory_amount:
          type: integer
        memory_unit:
          $ref: "#/components/schemas/StorageUnit"
        data_egress_monthly_amount:
          type: integer
        data_egress_monthly_unit:
          $ref: "#/components/schemas/StorageUnit"
    ClassificationLevel:
      description: "Part of DOW, Classification Level table fields"
      properties:
        classification:
          type: string
          enum:
            - Unclassified
            - Top Secret
            - Secret
        impact_level:
          type: string
          enum:
            - IL2
            - IL4
            - IL5
            - IL6
    StorageUnit:
      description: "Part of DOW, used in EnvironmentInstance schema"
      type: string
      enum:
        - GB
        - TB
    PerformanceRequirements:
      description: >
        Part of DOW, encapsulates all data for 4. Performance Requirements and its subtasks. 
        On the API side, the subtasks will filter through the provided required_services.service_offerings
        to create the subtasks fields.
      properties:
        required_services:
          type: array
          items:
            $ref: "#/components/schemas/RequiredService"
    RequiredService:
      description: "Part of DOW, represents a single required service"
      properties:
        applicable_classification_levels:
          type: array
          items:
            $ref: "#/components/schemas/ClassificationLevel"
        usage_description:
          type: string
        need_for_entire_TO_duration:
          type: boolean
        applicable_periods:
          type: array
          items:
            $ref: "#/components/schemas/Period"
        service_offerings: # represents the "Select Service Offerings" field
          type: array
          items:
            $ref: "#/components/schemas/ServiceOffering"
        other_service_offering:
          type: string
    Period:
      description: "Part of DOW, represents Period Table fields"
      properties:
        period_type:
          type: string
          enum:
            - Base
            - Option
        period_unit_count:
          type: integer
        period_unit:
          type: string
          enum:
            - Day(s)
            - Week(s)
            - Month(s)
            - Year(s)
        option_order:
          type: integer
    ServiceOffering:
      description: "Part of DOW, represents a single Service Offering (Service Offering table)"
      properties:
        service_offering_group:
          type: string
          enum:
            - Advanced Technology and Algorithmic Techniques (Machine Learning)
            - Advisory and Assistance
            - Applications
            - Compute
            - Database with Storage
            - Developer Tools and Services
            - Edge Computing and Tactical Edge (TE)
            - General IaaS, PaaS, and SaaS
            - Internet of Things (IoT)
            - Networking
            - Security
            - Training
        name:
          type: string
    PeriodOfPerformance:
      description: "Part of DOW, represents a single Period of Performance"
      properties:
        base_period:
          $ref: "#/components/schemas/Period"
        option_periods:
          type: array
          items:
            $ref: "#/components/schemas/Period"
        pop_start_request:
          type: boolean
        requested_pop_start_date:
          type: string
          format: date
          example: "2021-07-01"
        time_frame:
          type: string
          enum:
            - No later than
            - No sooner than
        recurring_requirement:
          type: boolean
    GFEOverview:
      description: "Part of DOW, represents GFE Overview fields"
      properties:
        dpas_unit_id:
          type: string
          maxLength: 6
        property_custodian_name:
          type: string
        dpas_custodian_number: # DPAS Custodian Number
          type: string
          maxLength: 6
        property_accountable:
          type: boolean
        gfe_or_gfp_furnished:
          type: boolean
    ContractConsiderations:
      description: "Part of DOW, represents Contract Considerations Table"
      properties:
        packaging_shipping_none_apply:
          type: boolean
        packaging_shipping_other:
          type: boolean
        packaging_shipping_other_explanation:
          type: string
        potential_conflict_of_interest:
          type: boolean
        conflict_of_interest_explanation:
          type: string
        contractor_provided_transfer:
          type: boolean
        contractor_required_training:
          type: boolean
        required_training_services: # This field looks incomplete on the SNOW side
          $ref: "#/components/schemas/TrainingCourses"
    TrainingCourses:
      description: "Part of DOW, part of schema for ContractConsiderations, includes training courses name and value"
      type: object
      properties:
        name:
          type: string
        value:
          type: string
    SensitiveInformation:
      description: "Part of DOW, represents Sensitive Information Table fields"
      properties:
        pii_present:
          type: boolean
        work_to_be_performed:
          type: string
        system_of_record_name:
          type: string
        FOIA_city_apo_fpo:
          type: string
        FOIA_country:
          type: string
        FOIA_street_address_1:
          type: string
        FOIA_street_address_2:
          type: string
        FOIA_address_type:
          type: string
          enum:
            - Foreign
            - Military
            - U.S.
        FOIA_state_province_code:
          type: string
        FOIA_full_name:
          type: string
        FOIA_email:
          type: string
          format: email
        FOIA_zip_postal_code:
          type: string
        BAA_required:
          type: boolean
        potential_to_be_harmful:
          type: boolean
        section_508_sufficient:
          type: boolean
        accessibility_reqs_508:
          type: string
