service: atat-sls-${opt:stage}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: azure
  region: ${opt:region, 'US East'}
  runtime: nodejs12
  stage: ${opt:stage, 'dev'}
  type: consumption
  useDotenv: true

plugins:
  - serverless-azure-functions
  - serverless-dotenv-plugin
  - serverless-webpack

package:
  patterns:
    - 'host.json'
    - '!local.settings.json'
    - '!.vscode/**'
    - '!**/*.test.js'

functions:
  get:
    handler: src/handlers/get.getQuote
    events:
      - http: true
        x-azure-settings:
          route: quotes
          methods:
            - GET
          authLevel: anonymous
  post:
    handler: src/handlers/post.addQuote
    events:
      - http: true
        x-azure-settings:
          route: quotes
          methods:
            - POST
          authLevel: anonymous