---
name: Deploy ATAT API Infrastructure

on:
  push:
    branches:
      - develop

jobs:
  deployInfrastructure:
    name: Test STS
    runs-on: ubuntu-latest
    permissions:
      # Required for the OIDC endpoint
      id-token: write
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2
      - name: Authenticate to AWS
        # The repo has not tagged a release with OIDC support so we must follow master
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-gov-west-1
          role-to-assume: arn:aws-us-gov:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/AtatPipelineDeploymentRole
          role-session-name: Deployment${{ github.run_id }}-${{ github.run_attempt }}
      - name: Test AWS access
        run: |
          aws sts get-caller-identity
