---
name: Run checks on PRs

on:
  pull_request_target:

jobs:
  validateContributorEmails:
    name: Check that contributors are from expected domains
    runs-on: ubuntu-latest
    steps:
      - name: Check contributors' email addresses
        id: get-commit-data
        uses: actions/github-script@v6
        with:
          script: |
            const query = `query($owner:String!, $name:String!, $number:Int!) {
              repository(owner: $owner, name: $name) {
                pullRequest(number: $number) {
                  commits(first: 250) {
                    totalCount
                    nodes {
                      commit {
                        author {
                          email
                        }
                      }
                    }
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              number: context.payload.pull_request.number,
            };
            console.log('Request variables: %j', variables);
            const result = await github.graphql(query, variables);
            const totalCommits = result.repository.pullRequest.commits.totalCount;
            // Get unique email addresses
            const commitEmails = [... new Set(result.repository.pullRequest.commits.nodes.map((node) => node.commit.author.email))];
            // Are all contributors' email addresses from an expected domain?
            const allFromExpectedDomains = commitEmails.every((email) => email.endsWith("@ccpo.mil") || email.endsWith("@mail.mil") || email.endsWith("@users.noreply.github.com"));

            core.setOutput("commit-count", totalCommits);
            core.setOutput("all-contributors-from-expected-domains", allFromExpectedDomains);

      - name: Message on too many commits
        if: ${{ fromJSON(steps.get-commit-data.outputs.commit-count) > 250 }}
        uses: actions/github-script@v6
        with:
          script: |
            message = `
            :warning: :rotating_light: **This branch has too many commits to validate** :rotating_light: :warning:

            Thanks for opening this pull request! We ensure that all contributor data matches certain patterns. Unfortunately,
            there are more than 250 commits on this PR which makes it a little challenging to validate.

            @dod-ccpo/platform-team Please pay extra attention to the contributor data on this pull request.
            `;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: message,
            });

      - name: Message on any contributor from unexpected domain
        if: ${{ steps.get-commit-data.outputs.all-contributors-from-expected-domains != 'true' }}
        uses: actions/github-script@v6
        with:
          script: |
            message = `
            :wave: **One or more commits are from an external contributor** :wave:
            
            Thanks for opening this pull request! It looks like one or more commits on this pull request are from an external
            contributor. Thanks for taking the time to make a contribution; it will be reviewed shortly.
            
            @dod-ccpo/platform-team Please ensure that all contributor data associated with this commit looks reasonable and
            that this is a contribution from an external contributor; make sure all commits from team members have proper email data
            associated with them.
            `;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: message,
            });

      - name: Message on all contributors from expected domains
        if: ${{ steps.get-commit-data.outputs.all-contributors-from-expected-domains == 'true' }}
        uses: actions/github-script@v6
        with:
          script: |
            message = `
            :white_check_mark: **All commits are from internal contributors at expected domains** :white_check_mark:

            Thanks for opening this pull request! It looks like all the contributors have set the email address for the commits.
            
            @dod-ccpo/platform-team Remember that anyone can set contributor information to any value. Please review the content
            of the pull request thoroughly, as always.
            `;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: message,
            });
